name: mandoob
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # retrofit apis calls
  retrofit: ^3.0.1+1
  # performs static analysis of Dart code
  analyzer: ^5.2.0
  # http client
  dio: ^4.0.6
  # serialization from and to json
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  # control response if failed or success
  dartz: ^0.10.1
  # internet checker (NOT SUPPORT WEB)
  internet_connection_checker: ^0.0.1+3
  # is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1
  # storage for simple data local
  shared_preferences: ^2.2.1
  # generator for data-classes
  freezed: ^2.3.2
  # The Material Design Icons Icon pack available as set of Flutter Icons
  material_design_icons_flutter: ^5.0.6595
  font_awesome_flutter: ^10.2.1
  # svg images
  flutter_svg: ^1.1.6
  # dependency injection
  get_it: ^7.2.0
  # animations exported as json
  lottie: ^1.2.0
  # Dart comes with a very decent Streams API out-of-the-box
  rxdart: ^0.27.4
  # Easy sidemenu is An easy to use side menu (bar)
  easy_sidemenu: ^0.3.1
  # Adaptive Scrollbar allows you to create one or more desktop-style scrollbars on a single screen
  adaptive_scrollbar: ^2.1.2
  cross_scroll: ^0.0.75
  # for translations
  easy_localization: ^3.0.1
  # Easily restart your application from scratch, losing any previous state.
  flutter_phoenix: ^1.1.0
  # responsive size
  responsive_sizer: ^3.2.0
  responsive_framework: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+3
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^7.4.0
  # add almost any kind of animated effect
  flutter_animate: ^4.1.0
  freezed_annotation: ^2.4.1
  timeline_tile: ^2.0.0
  animated_bottom_navigation_bar:
  conditional_builder_null_safety: ^0.0.6
  awesome_snackbar_content:
  path_provider:
  image_network:
  shimmer: ^3.0.0
  #cubit
  flutter_bloc:
  easy_date_timeline: ^1.0.3
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # create auto generator files in project
  retrofit_generator: ^4.2.0
  # native splash
  flutter_native_splash: ^2.2.15
  # Change App Package Name with single command. It makes the process very easy and fast.
  change_app_package_name: ^1.1.0

  build_runner: ^2.1.10

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/drower/
    - assets/images/botomnavg/
    - assets/json/
    - assets/translations/ar-EGY.json
    - assets/translations/en-US.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Segoe-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxygen/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen/Oxygen-Light.ttf
          weight: 300
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  image: assets/logo.png
  color: "#fefefe"
  image_dark: assets/logo.png
  color_dark: "#fefefe"
  android: true
  ios: true
  android_12:
    image: assets/logo.png
    icon_background_color: "#fefefe"
    image_dark: assets/logo.png
    icon_background_color_dark: "#fefefe"